package com.iti.jets.tourism.test;
// Generated Apr 24, 2015 4:17:55 PM by Hibernate Tools 4.3.1


import sun.misc.BASE64Decoder;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;

/**
 * ImageData generated by hbm2java
 */
public class ImageData  implements java.io.Serializable {


     private int idImageData;
     private String imageContent;
     private String mimeType;
     private String imageName;

    public ImageData() {
    }

	
    public ImageData(int idImageData) {
        this.idImageData = idImageData;
    }
    public ImageData(int idImageData, String imageContent, String mimeType, String imageName) {
       this.idImageData = idImageData;
       this.imageContent = imageContent;
       this.mimeType = mimeType;
       this.imageName = imageName;
    }
   
    public int getIdImageData() {
        return this.idImageData;
    }
    
    public void setIdImageData(int idImageData) {
        this.idImageData = idImageData;
    }
    public String getImageContent() {
        return this.imageContent;
    }
    
    public void setImageContent(String imageContent) {
        this.imageContent = imageContent;
    }
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }


    public static void readImage(String imageString) {

        byte[] imageByte;
        try {

            BASE64Decoder decoder = new BASE64Decoder();
            imageByte = decoder.decodeBuffer(imageString);
            ByteArrayInputStream bis = new ByteArrayInputStream(imageByte);
            BufferedImage image = ImageIO.read(bis);
            ImageIO.write(image, "jpg", new File("D:\\out.jpg"));
            bis.close();
            System.out.println(image);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}


